### ISSUE TITLE
No version pinned in requirements causes random behavior and different versions installed each time

### ISSUE THREAD

**Issue by Elameri-ID** [nolar/kopf#1147]
### Long story short

https://github.com/nolar/kopf/issues/1146

### Kopf version

all

### Kubernetes version

all

### Python version

all

### Code

```python
# Everything needed to develop (test, debug) the framework.
# The runtime dependencies of the framework, as if via `pip install kopf`.
-e .
aresponses
astpath[xpath]
certbuilder
certvalidator
codecov
coverage
coveralls
freezegun
import-linter
isort
lxml
mypy==1.13.0
pre-commit
pyngrok
pytest>=6.0.0
pytest-aiohttp
pytest-asyncio
pytest-cov
pytest-mock
pytest-timeout
types-PyYAML
types-setuptools


    install_requires=[
        'typing_extensions',    # 0.20 MB
        'python-json-logger',   # 0.05 MB
        'iso8601',              # 0.07 MB
        'click',                # 0.60 MB
        'aiohttp',              # 7.80 MB
        'aiohttp>=3.9.0; python_version>="3.12"',
        'pyyaml',               # 0.90 MB
    ],
```

### Logs

```none
Traceback (most recent call last):
  File "/usr/local/bin/kopf", line 5, in <module>
    from kopf.cli import main
  File "/usr/local/lib/python3.12/site-packages/kopf/__init__.py", line 111, in <module>
    from kopf._core.actions.loggers import (
  File "/usr/local/lib/python3.12/site-packages/kopf/_core/actions/loggers.py", line 16, in <module>
    import pythonjsonlogger.jsonlogger
ModuleNotFoundError: No module named 'pythonjsonlogger.jsonlogger'
```

**Comment by nolar** [comment]
In CI (requirements.txt), that is done deliberately — in order to detect when Kopf or its CI start failing due to new releases of any dependency (at least when I watched over the CI regularly).

As for the `setup.py` requirements — that is critical. Kopf is a library, not the final application, so it must be as relaxed in requirements as possible, to let the real apps manage their pinned requerements. The only restriction that Kopf uses is `>=` for the versions with the minimal functional requirements, and rarely `<` for major version limitations with known issues.

The operator developers, i.e. the developers of the final applications packaged as docker images, should pin their requirements — as one of the established best practices in the Python world (be that pip/setuptools, pip-env, poetry, or any other packaging system).
