### ISSUE TITLE
Is there anyway to AND handlers?

### ISSUE THREAD

**Issue by euan-tilley** [nolar/kopf#620]
## Question

I need to handle the creation of a new CRD resource but before doing anything wait for a k8s job to finish. 
Is there a way to AND an on.create & a on.event handler?

## Checklist

- [*] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [*] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords
on.create 
on.event

**Comment by nolar** [comment]
Generally, no. But you can store something into that CR's field — e.g. `.status.jobisdone` or `.status.jobs.{id}` — when the job(s) is/are done (from on.event?), and track that field via on-update/on-field of the CR:

```python
@kopf.on.field("mycr"..., field='status.jobisdone')
def jobsdonefn(old, new, **_):
    print(f"{old} => {new}")
```

This is how we do it, more or less.

PS: For patching the CR, use your preferred K8s API client. Kopf has no automatic cross-resource information exchange yet.

**Comment by euan-tilley** [comment]
Thanks for this. 
However I have realised that there is no event generated for job completion so this will not work. 
I am now manually checking for job completion & raising a `kopf.TemporaryError` if not. This works well apart from the extra ERROR events that get raised. I understand that `settings.posting` can be changed in `on.startup` but was wondering if it can be dynamically changed in a `on.create` handler?

**Comment by nolar** [comment]
To avoid  `TemporaryError`, consider using `@kopf.timer()` or `@kopf.daemon()` to periodically poll for something. 

They also respect the label/annotation filters (and [field/value filters](https://kopf.readthedocs.io/en/latest/filters/#field-filters) since [1.29.0rc1](https://github.com/nolar/kopf/releases/tag/1.29.0rc1)), so, once the desired state is reached, a timer/daemon can exclude itself from execution forever. Something like this:

```python
import random
import kopf

@kopf.timer('kex', interval=5, labels={'i-am-done': kopf.ABSENT})
def poll_for_something(patch, **_):
    if random.randint(0, 9) == 0:
        patch.metadata.labels['i-am-done'] = 'yep'
```

```python
import random
import time
import kopf

@kopf.daemon('kex', labels={'i-am-done': kopf.ABSENT})
def poll_for_something(stopped, patch, **_):
    while not stopped:
        if random.randint(0, 9) == 0:
            patch.metadata.labels['i-am-done'] = 'yep'
            return
        time.sleep(5)
```

In this case, `randint()` should be a Job/Pod polling.

---

Just for information: For a similar use-case, we use the following solution:

1. When a parent CR is created, we create a `Job` with `spec.template.metadata.labels.owned-by-parent: name` (as an example) — i.e. the pod gets the label, not the job. Where `name` is the name of the parent resource, as taken from kwargs of the handler — it will be needed in the step 4.
2. We then watch for `@kopf.on.event('', 'v1', 'pods', labels={'owned-by-parent': kopf.PRESENT})` — i.e. all pods that do have this label with any value, and ignore all those that don't have it (incl. the operator iself).
3. On every change of a pod, we check for the pod's completion status (forgot how, something about `.status.phase`), and, 
4. When the calculation evaluates to true, i.e. it is completed (or failed), patch the parent CR with the name taken from `labels['owned-by-parent']` — via a regular K8s API client (pykube-ng in our case). All you need for that is the CRD's name (group+version+plural), CR's name and namespace — and you have it all.

It is very important that the operator is running at the moment when the pod is completed, i.e. not down. Otherwise, the pod will be garbage-collected soon, and this information will be lost. You can try using more reliable `@kopf.on.update('pods', field='status.phase', labels={...})` here (`field=` only works in 1.29.0rc1) — should work, should prevent the pods' garbage collection; I just never tried it.

This way, we report the pod's completion back to the parent resource by skipping an intermediate `Job` resource. 

Worth noting that it works for one-pod jobs in our case. For many-pod jobs, you have to implement a more advanced logic for deciding about the job completion, but still the concept is still the same: label & filter.

**Comment by euan-tilley** [comment]
Ok thanks for the details, this will be helpful
