### ISSUE TITLE
pip install kopf;  command "kopf" not found

### ISSUE THREAD

**Issue by lazywhite** [nolar/kopf#649]
```
(kopf) [root@control-plane envs]# pip install kopf
Collecting kopf
  Using cached kopf-0.0-py3-none-any.whl (1.1 kB)
Installing collected packages: kopf
Successfully installed kopf-0.0
```
size of kopf package is noly 1.1kB

```
(kopf) [root@control-plane envs]# kopf
bash: kopf: command not found...
```

**Comment by nolar** [comment]
The latest version of Kopf is 0.28.3: https://pypi.org/project/kopf/#history

Please check if pip works fine with PyPI. Try running with `pip install -v kopf` and checking why does it fetch the irrelevant version 0.0.

Some hints on the Python version, pip version, and the virtualenv approach would be nice to have.

**Comment by epierotto** [comment]
kopf needs at least: `python_requires='>=3.7'`, maybe is that.
https://github.com/nolar/kopf/blob/master/setup.py#L40

**Comment by bergerx** [comment]
This is likely because kopf-0.0 didnt have a python version constraint, likely because it was just an initial package creation:
https://github.com/nolar/kopf/blob/fae0942780783cea84c28ebb699fef1e27d425b0/setup.py#L1-L15

But all later versions have a constraint:
https://github.com/nolar/kopf/blob/433709dc8846f4b399e98f04c843362230357225/setup.py#L40

So it's more likely that you have an old Python version and 0.0 is picked due to not having any constraint. Check which version of Python is your pip is using with `pip --version`.

**Comment by nolar** [comment]
Indeed! Thanks for pointing that out (the error looked weird to me initial, but now, it is totally clear). I've ["yanked"](https://pypi.org/help/#yanked) the version 0.0 from PyPI, so that it does not cause this confusion anymore.

UPD: Actually, deleted. Why would anybody install an empty placeholder package?

**Comment by nolar** [comment]
UPD: Actually, deleted. Why would anybody install an empty placeholder package?
