### ISSUE TITLE
Can I get a good example where this project is used?

### ISSUE THREAD

**Issue by caffeinism** [nolar/kopf#802]
## Question

I am someone who learns from code.

I've read the documentation, but I'm still stuck in several areas. (For example, good yaml template method. Many kubernetes applications use go template. But this is because kubernetes and many applications use go. So, is it better to use Jinja2? But I haven't been able to find such a use case.)

Any good examples? It would be nice if you could recommend it.

Thanks for the good project.

## Checklist

- [x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

template, open source, repository

**Comment by nolar** [comment]
Hello. This is a good question. Sadly, I do not gather the information on how and where Kopf is used, and do not classify that by usage type — so I have no answer to that question.

Besides, since Kopf's main aim is to simplify the creation of ad-hoc operators in the first place (by removing the infra hassle), I would expect that most of them are not even open-sourced. Most likely, it is used in some in-house tools.

You can probably find some uses in what GitHub reports as dependents:

* https://github.com/nolar/kopf/network/dependents

Some people also reported their usage here:

* https://github.com/nolar/kopf/discussions/100

I cannot tell what usage is "good" or "not good".

If you find any good examples of Kopf usage, feel free to report there.
