### ISSUE TITLE
Can parallel handler contexts affect each other?

### ISSUE THREAD

**Issue by freefood89** [nolar/kopf#867]
### Keywords

parallelism, error handling

### Problem

I'm completely baffled by this issue and would appreciate any pointers..

1. The operator was working without issues until someone deployed 3 custom resources that triggered an uncaught exception in the delete handler. 
2. While the exception was being raised, other instances of this resource started experiencing unexplained issues during the execution of the creation handler. Simple code that creates data classes from the `spec` handler argument started returning a `dict`. I am not sure which ones were created in which order.
3. I fixed my mistake (in 1) and redeployed
4. The create handler failed one last time until the delete handlers successfully executed for each of the 3 erroneous resources (from 1).
5. FInally, the create handlers successfully executed

This is not the first time fixing an issue seemingly "unblocked" processing of other resources. I thought that the handlers were executing in parallel. Am I missing something here? Do the resources needed to be processed in order unless I raise a TemporaryError?

I start kopf using `kopf run --standalone handlers.py`. Is there a parallelism option I am not specifying?

**Comment by nolar** [comment]
Hello.

Regarding the order and parallelism: handlers for different resource objects can be executed in any order. Kopf demultiplexes the stream of a single resource kind into multiple pseudo-parallel workers of each resource object.

Please note the "pseudo-parallel" remark. Since Kopf runs in an asyncio event loop, nothing is truly parallel, it is concurrent (cooperative concurrency). If the handlers are `async def`, having heavy blocking operations in them can be a huge problem for the whole operator: https://kopf.readthedocs.io/en/stable/async/

However, if the handlers are just `def` (synchronous), they are executed in the asyncio executors (thread pools). In that case, they can be truly parallel, but Kopf cannot guarantee that.

Having a code snippet would be helpful. With no context about your operator, it is difficult to understand what exactly has failed and why. Currently, I cannot help based on this description of the problem, sorry.

**Comment by freefood89** [comment]
Thanks! I will try to reproduce it and post another question with more details
