### ISSUE TITLE
stopped.wait(...) should take a callable

### ISSUE THREAD

**Issue by brianthelion** [nolar/kopf#931]
### Problem

`kopf.daemon` suffers from a problem that reduces its utility. Namely, if the _synchronous_ `daemon` needs to take action on an _asynchronous_ event, it has no choice but to sit in a polling loop and use `stopped.wait(...)` so as to not starve other threads.

### Proposal

Either (1) `stopped.wait(...)` should accept a callable or (2) `stopped` should have a `.wait_for(...)` method that accepts a callable. 

The method should only return when either (a) the callable returns, (b) the timeout is reached, or (c) `stopped` evaluates to `True`. The callable's value could then be made available as an attribute of `stopped`.

### Code

Consider the [Queue example](https://kopf.readthedocs.io/en/latest/memos/?highlight=queue#operator-memos), but with one Queue per `FooObject`. In this case, we would _ideally_ like to implement the `background(...)` Thread as a `kopf.daemon`. But due to the problem above, this is not possible. Specifically, we would like to change:

```python
@kopf.on.startup()
def start_background_worker(memo: kopf.Memo, **_):
    memo.my_queue = queue.Queue()
    memo.my_thread = threading.Thread(target=background, args=(memo.my_queue,))
    memo.my_thread.start()

def background(queue: queue.Queue):
    while True:
        item = queue.get()
        if item is None:
            break
        else:
            print(item)
```

to

```python
@kopf.on.create(...)
def foo_object_create_queue(memo, name, namespace, **_):
    memo.queues[(name, namespace)] = queue.Queue()

@kopf.daemon(....)
def foo_object_queue_manager(stopped, memo, name, namespace, **_):
    queue = memo.queues[(name, namespace)]
    while not stopped:
        stopped.wait_for(queue.get) # <=== Calling queue.get() directly would starve other threads
        item = stopped.waited_value
        if item is None:
            break
        else:
            print(item)
```

### Additional information

Without a `kopf.daemon`-based solution, we end up spawning and managing our own Thread as in the [Queue example](https://kopf.readthedocs.io/en/latest/memos/?highlight=queue#operator-memos) and avoiding `kopf.daemon` altogether.

**Comment by nolar** [comment]
Hello. Thanks for the question.

`stopped.wait()` is intended to be a replacement for `time.sleep()` with one extra exiting condition, so it also inherits all its limitations.

Regarding the callback `queue.get` — I am not sure how to implement such a sleep routine with a synchronous method: since `queue.get()` is blocking, when `stopped.wait()` calls it, it will be blocked there anyway — and will not be able even to check for timeouts or stopping conditions.

What I can suggest here is to consider making an async daemon and utilise all the benefits of asyncio: in particular, the ability to be "cancelled" (asyncio.CancelledError) at any moment in time in any coroutine.

Then, depending on the nature of the queue, I would also recommend to make the queue asynchronous if possible. If not, then use the thread-pool executor of asyncio.

```python
import kopf
import asyncio

@kopf.on.startup(...)
async def remember_the_event_loop(memo: kopf.Memo, **_):
    memo.operator_loop = asyncio.get_running_loop()

@kopf.on.create(...)
@kopf.on.resume(...)  # <<< also keep this
async def foo_object_create_queue(memo: kopf.Memo, **_):
    memo.my_queue = asyncio.Queue()

@kopf.daemon(....)
async def foo_object_queue_manager(memo, **_):
    queue = memo.my_queue
    while True:
        item = await memo.my_queue.get()
        if item is None:
            break
        else:
            print(item)

```

In this case, `.get()` waits forever but remains interruptable by asyncio. Kopf cancels (interrupts) the daemon with `asyncio.CancelledError` as soon as it wants it to stop (something that is impossible with sync threads/functions without involving `stopped.wait()`).

Note that I have removed all the mentions of `stopped` and `stopped.wait()` — there is simply no need for that in the async world — even in the `while True` cycle.

When you want to put to an asyncio queue from a sync function, use one of:

```python
# It can raise `QueueFull` if the queue is size-limited; not a problem for unlimited queues.
some_queue.put_nowait(some_item)  

# From another thread (incl. synchronous handlers):
memo.operator_loop.call_soon_threadsafe(some_queue.put, some_item)
```

**Comment by brianthelion** [comment]
@nolar 

> When you want to put to an asyncio queue from a sync function, use one of:
> ```
> # It can raise `QueueFull` if the queue is size-limited; not a problem for unlimited queues.
> some_queue.put_nowait(some_item)  
> 
> # From another thread (incl. synchronous handlers):
> memo.operator_loop.call_soon_threadsafe(some_queue.put, some_item)
> ```

This is likely what I'll have to do, as refactoring my controller to use `async` throughout is proving tricky.

**Comment by nolar** [comment]
I assume this question is answered. If now, feel free to reopen or ask a new question in a new issue (or in a new discussion).
